// Generated by xlsx2verilog.py. Do not edit by hand.
module ibex_if_stage (
    input wire clk_i,
    input wire rst_ni,
    input wire [31:0] boot_addr_i,
    input wire req_i,
    output wire instr_req_o,
    output wire [31:0] instr_addr_o,
    input wire instr_gnt_i,
    input wire instr_rvalid_i,
    input wire [31:0] instr_rdata_i,
    input wire instr_bus_err_i,
    output wire instr_valid_id_o,
    output wire [31:0] instr_rdata_id_o,
    input wire id_in_ready_i,
    input wire dummy_instr_en_i,
    input wire [2:0] dummy_instr_mask_i,
    input wire dummy_instr_seed_en_i,
    input wire [31:0] dummy_instr_seed_i,
    output wire if_busy_o
);

    // Module placeholder: drive every output to zero.
    assign instr_req_o = 1'b0;
    assign instr_addr_o = 32'b0;
    assign instr_valid_id_o = 1'b0;
    assign instr_rdata_id_o = 32'b0;
    assign if_busy_o = 1'b0;

endmodule
