// Generated by xlsx2verilog.py. Do not edit by hand.
module ibex_core (
    input  wire        clk_i,
    input  wire        rst_ni,
    input  wire [31:0] boot_addr_i,
    output wire        instr_req_o,
    output wire [31:0] instr_addr_o,
    input  wire        instr_gnt_i,
    input  wire        instr_rvalid_i,
    input  wire [31:0] instr_rdata_i,
    input  wire        instr_err_i,
    output wire        data_req_o,
    output wire [31:0] data_addr_o,
    output wire        data_we_o,
    output wire [3:0]  data_be_o,
    output wire [31:0] data_wdata_o,
    input  wire        data_gnt_i,
    input  wire        data_rvalid_i,
    input  wire [31:0] data_rdata_i,
    input  wire        data_err_i
);

    // Internal child-to-child connections.
    wire w_req_i_to_instr_req_o;
    wire w_instr_valid_id_o_to_instr_valid_i;
    wire [31:0] w_instr_rdata_id_o_to_instr_rdata_i;
    wire w_id_in_ready_i_to_id_in_ready_o;
    wire w_lsu_resp_valid_i_to_lsu_resp_valid_o;
    wire w_lsu_req_o_to_lsu_req_i;
    wire w_lsu_we_o_to_lsu_we_i;
    wire [1:0] w_lsu_type_o_to_lsu_type_i;
    wire w_lsu_sign_ext_o_to_lsu_sign_ext_i;
    wire [31:0] w_lsu_wdata_o_to_lsu_wdata_i;
    wire w_lsu_req_done_i_to_lsu_req_done_o;
    wire w_lsu_addr_incr_req_i_to_addr_incr_req_o;
    wire [31:0] w_lsu_addr_last_i_to_addr_last_o;
    wire w_lsu_load_err_i_to_load_err_o;
    wire w_lsu_load_resp_intg_err_i_to_load_resp_intg_err_o;
    wire w_lsu_store_err_i_to_store_err_o;
    wire w_lsu_store_resp_intg_err_i_to_store_resp_intg_err_o;
    wire [31:0] w_alu_adder_result_ex_o_to_adder_result_ex_i;

    ibex_if_stage u_ibex_if_stage (
        .clk_i                 (clk_i),
        .rst_ni                (rst_ni),
        .boot_addr_i           (boot_addr_i),
        .req_i                 (w_req_i_to_instr_req_o),
        .instr_req_o           (instr_req_o),
        .instr_addr_o          (instr_addr_o),
        .instr_gnt_i           (instr_gnt_i),
        .instr_rvalid_i        (instr_rvalid_i),
        .instr_rdata_i         (instr_rdata_i),
        .instr_bus_err_i       (instr_err_i),
        .instr_valid_id_o      (w_instr_valid_id_o_to_instr_valid_i),
        .instr_rdata_id_o      (w_instr_rdata_id_o_to_instr_rdata_i),
        .id_in_ready_i         (w_id_in_ready_i_to_id_in_ready_o),
        .dummy_instr_en_i      (1'b0),
        .dummy_instr_mask_i    (3'b0),
        .dummy_instr_seed_en_i (1'b0),
        .dummy_instr_seed_i    (32'b0),
        .if_busy_o             ()
    );

    ibex_id_stage u_ibex_id_stage (
        .clk_i                     (clk_i),
        .rst_ni                    (rst_ni),
        .instr_valid_i             (w_instr_valid_id_o_to_instr_valid_i),
        .instr_rdata_i             (w_instr_rdata_id_o_to_instr_rdata_i),
        .instr_req_o               (w_req_i_to_instr_req_o),
        .id_in_ready_o             (w_id_in_ready_i_to_id_in_ready_o),
        .lsu_resp_valid_i          (w_lsu_resp_valid_i_to_lsu_resp_valid_o),
        .lsu_req_o                 (w_lsu_req_o_to_lsu_req_i),
        .lsu_we_o                  (w_lsu_we_o_to_lsu_we_i),
        .lsu_type_o                (w_lsu_type_o_to_lsu_type_i),
        .lsu_sign_ext_o            (w_lsu_sign_ext_o_to_lsu_sign_ext_i),
        .lsu_wdata_o               (w_lsu_wdata_o_to_lsu_wdata_i),
        .lsu_req_done_i            (w_lsu_req_done_i_to_lsu_req_done_o),
        .lsu_addr_incr_req_i       (w_lsu_addr_incr_req_i_to_addr_incr_req_o),
        .lsu_addr_last_i           (w_lsu_addr_last_i_to_addr_last_o),
        .lsu_load_err_i            (w_lsu_load_err_i_to_load_err_o),
        .lsu_load_resp_intg_err_i  (w_lsu_load_resp_intg_err_i_to_load_resp_intg_err_o),
        .lsu_store_err_i           (w_lsu_store_err_i_to_store_err_o),
        .lsu_store_resp_intg_err_i (w_lsu_store_resp_intg_err_i_to_store_resp_intg_err_o),
        .alu_adder_result_ex_o     (w_alu_adder_result_ex_o_to_adder_result_ex_i)
    );

    ibex_load_store_unit u_ibex_load_store_unit (
        .clk_i                 (clk_i),
        .rst_ni                (rst_ni),
        .data_req_o            (data_req_o),
        .data_gnt_i            (data_gnt_i),
        .data_rvalid_i         (data_rvalid_i),
        .data_bus_err_i        (data_err_i),
        .data_pmp_err_i        (1'b0),
        .data_addr_o           (data_addr_o),
        .data_we_o             (data_we_o),
        .data_be_o             (data_be_o),
        .data_wdata_o          (data_wdata_o),
        .data_rdata_i          (data_rdata_i),
        .lsu_we_i              (w_lsu_we_o_to_lsu_we_i),
        .lsu_type_i            (w_lsu_type_o_to_lsu_type_i),
        .lsu_wdata_i           (w_lsu_wdata_o_to_lsu_wdata_i),
        .lsu_sign_ext_i        (w_lsu_sign_ext_o_to_lsu_sign_ext_i),
        .lsu_rdata_o           (),
        .lsu_rdata_valid_o     (),
        .lsu_req_i             (w_lsu_req_o_to_lsu_req_i),
        .adder_result_ex_i     (w_alu_adder_result_ex_o_to_adder_result_ex_i),
        .addr_incr_req_o       (w_lsu_addr_incr_req_i_to_addr_incr_req_o),
        .addr_last_o           (w_lsu_addr_last_i_to_addr_last_o),
        .lsu_req_done_o        (w_lsu_req_done_i_to_lsu_req_done_o),
        .lsu_resp_valid_o      (w_lsu_resp_valid_i_to_lsu_resp_valid_o),
        .load_err_o            (w_lsu_load_err_i_to_load_err_o),
        .load_resp_intg_err_o  (w_lsu_load_resp_intg_err_i_to_load_resp_intg_err_o),
        .store_err_o           (w_lsu_store_err_i_to_store_err_o),
        .store_resp_intg_err_o (w_lsu_store_resp_intg_err_i_to_store_resp_intg_err_o),
        .busy_o                (),
        .perf_load_o           (),
        .perf_store_o          ()
    );

endmodule
