// Generated by xlsx2verilog.py. Do not edit by hand.
module ibex_dummy_instr (
    input wire clk_i,
    input wire rst_ni,
    input wire dummy_instr_en_i,
    input wire [2:0] dummy_instr_mask_i,
    input wire dummy_instr_seed_en_i,
    input wire [31:0] dummy_instr_seed_i,
    input wire fetch_valid_i,
    input wire id_in_ready_i,
    output wire insert_dummy_instr_o,
    output wire [31:0] dummy_instr_data_o
);

    // Module placeholder: drive every output to zero.
    assign insert_dummy_instr_o = 1'b0;
    assign dummy_instr_data_o = 32'b0;

endmodule
