// Generated by xlsx2verilog.py. Do not edit by hand.
module ibex_id_stage (
    input wire clk_i,
    input wire rst_ni,
    input wire instr_valid_i,
    input wire [31:0] instr_rdata_i,
    output wire instr_req_o,
    output wire id_in_ready_o,
    input wire lsu_resp_valid_i,
    output wire lsu_req_o,
    output wire lsu_we_o,
    output wire [1:0] lsu_type_o,
    output wire lsu_sign_ext_o,
    output wire [31:0] lsu_wdata_o,
    input wire lsu_req_done_i,
    input wire lsu_addr_incr_req_i,
    input wire [31:0] lsu_addr_last_i,
    input wire lsu_load_err_i,
    input wire lsu_load_resp_intg_err_i,
    input wire lsu_store_err_i,
    input wire lsu_store_resp_intg_err_i,
    output wire [31:0] alu_adder_result_ex_o
);

    // Module placeholder: drive every output to zero.
    assign instr_req_o = 1'b0;
    assign id_in_ready_o = 1'b0;
    assign lsu_req_o = 1'b0;
    assign lsu_we_o = 1'b0;
    assign lsu_type_o = 2'b0;
    assign lsu_sign_ext_o = 1'b0;
    assign lsu_wdata_o = 32'b0;
    assign alu_adder_result_ex_o = 32'b0;

endmodule
