// Generated by xlsx2verilog.py. Do not edit by hand.
module ibex_load_store_unit (
    input wire clk_i,
    input wire rst_ni,
    output wire data_req_o,
    input wire data_gnt_i,
    input wire data_rvalid_i,
    input wire data_bus_err_i,
    input wire data_pmp_err_i,
    output wire [31:0] data_addr_o,
    output wire data_we_o,
    output wire [3:0] data_be_o,
    output wire [31:0] data_wdata_o,
    input wire [31:0] data_rdata_i,
    input wire lsu_we_i,
    input wire [1:0] lsu_type_i,
    input wire [31:0] lsu_wdata_i,
    input wire lsu_sign_ext_i,
    output wire [31:0] lsu_rdata_o,
    output wire lsu_rdata_valid_o,
    input wire lsu_req_i,
    input wire [31:0] adder_result_ex_i,
    output wire addr_incr_req_o,
    output wire [31:0] addr_last_o,
    output wire lsu_req_done_o,
    output wire lsu_resp_valid_o,
    output wire load_err_o,
    output wire load_resp_intg_err_o,
    output wire store_err_o,
    output wire store_resp_intg_err_o,
    output wire busy_o,
    output wire perf_load_o,
    output wire perf_store_o
);

    // Module placeholder: drive every output to zero.
    assign data_req_o = 1'b0;
    assign data_addr_o = 32'b0;
    assign data_we_o = 1'b0;
    assign data_be_o = 4'b0;
    assign data_wdata_o = 32'b0;
    assign lsu_rdata_o = 32'b0;
    assign lsu_rdata_valid_o = 1'b0;
    assign addr_incr_req_o = 1'b0;
    assign addr_last_o = 32'b0;
    assign lsu_req_done_o = 1'b0;
    assign lsu_resp_valid_o = 1'b0;
    assign load_err_o = 1'b0;
    assign load_resp_intg_err_o = 1'b0;
    assign store_err_o = 1'b0;
    assign store_resp_intg_err_o = 1'b0;
    assign busy_o = 1'b0;
    assign perf_load_o = 1'b0;
    assign perf_store_o = 1'b0;

endmodule
