// Generated by xlsx2verilog.py. Do not edit by hand.
module ibex_if_stage (
    input  wire        clk_i,
    input  wire        rst_ni,
    input  wire [31:0] boot_addr_i,
    input  wire        req_i,
    output wire        instr_req_o,
    output wire [31:0] instr_addr_o,
    input  wire        instr_gnt_i,
    input  wire        instr_rvalid_i,
    input  wire [31:0] instr_rdata_i,
    input  wire        instr_bus_err_i,
    output wire        instr_valid_id_o,
    output wire [31:0] instr_rdata_id_o,
    input  wire        id_in_ready_i,
    input  wire        dummy_instr_en_i,
    input  wire [2:0]  dummy_instr_mask_i,
    input  wire        dummy_instr_seed_en_i,
    input  wire [31:0] dummy_instr_seed_i,
    output wire        if_busy_o
);

    // Internal child-to-child connections.
    wire w_valid_o_to_valid_i_to_fetch_valid_i;
    wire [31:0] w_rdata_o_to_instr_i;

    // TOP outputs without a child driver are tied to zero.
    assign instr_valid_id_o = 1'b0;
    assign instr_rdata_id_o = 32'b0;

    ibex_prefetch_buffer u_ibex_prefetch_buffer (
        .clk_i          (clk_i),
        .rst_ni         (rst_ni),
        .req_i          (req_i),
        .branch_i       (1'b0),
        .addr_i         (32'b0),
        .ready_i        (1'b0),
        .valid_o        (w_valid_o_to_valid_i_to_fetch_valid_i),
        .rdata_o        (w_rdata_o_to_instr_i),
        .addr_o         (),
        .err_o          (),
        .err_plus2_o    (),
        .instr_req_o    (instr_req_o),
        .instr_gnt_i    (instr_gnt_i),
        .instr_addr_o   (instr_addr_o),
        .instr_rdata_i  (instr_rdata_i),
        .instr_err_i    (instr_bus_err_i),
        .instr_rvalid_i (instr_rvalid_i),
        .busy_o         (if_busy_o)
    );

    ibex_compressed_decoder u_ibex_compressed_decoder (
        .clk_i            (clk_i),
        .rst_ni           (rst_ni),
        .valid_i          (w_valid_o_to_valid_i_to_fetch_valid_i),
        .id_in_ready_i    (id_in_ready_i),
        .instr_i          (w_rdata_o_to_instr_i),
        .instr_o          (),
        .is_compressed_o  (),
        .gets_expanded_o  (),
        .flush_expanded_i (1'b0),
        .illegal_instr_o  ()
    );

    ibex_dummy_instr u_ibex_dummy_instr (
        .clk_i                 (clk_i),
        .rst_ni                (rst_ni),
        .dummy_instr_en_i      (dummy_instr_en_i),
        .dummy_instr_mask_i    (dummy_instr_mask_i),
        .dummy_instr_seed_en_i (dummy_instr_seed_en_i),
        .dummy_instr_seed_i    (dummy_instr_seed_i),
        .fetch_valid_i         (w_valid_o_to_valid_i_to_fetch_valid_i),
        .id_in_ready_i         (id_in_ready_i),
        .insert_dummy_instr_o  (),
        .dummy_instr_data_o    ()
    );

endmodule
