// Generated by xlsx2verilog.py. Do not edit by hand.
module ibex_prefetch_buffer (
    input  wire        clk_i,
    input  wire        rst_ni,
    input  wire        req_i,
    input  wire        branch_i,
    input  wire [31:0] addr_i,
    input  wire        ready_i,
    output wire        valid_o,
    output wire [31:0] rdata_o,
    output wire [31:0] addr_o,
    output wire        err_o,
    output wire        err_plus2_o,
    output wire        instr_req_o,
    input  wire        instr_gnt_i,
    output wire [31:0] instr_addr_o,
    input  wire [31:0] instr_rdata_i,
    input  wire        instr_err_i,
    input  wire        instr_rvalid_i,
    output wire        busy_o
);

    // Module placeholder: drive every output to zero.
    assign valid_o = 1'b0;
    assign rdata_o = 32'b0;
    assign addr_o = 32'b0;
    assign err_o = 1'b0;
    assign err_plus2_o = 1'b0;
    assign instr_req_o = 1'b0;
    assign instr_addr_o = 32'b0;
    assign busy_o = 1'b0;

endmodule
