/*USER CODE BEGIN file header*/
//******************
// Design by: aaa
// Project name: bbb
//
//******************
/*USER CODE END   file header*/

// Generated by xlsx2verilog.py. Do not edit outside USER CODE regions.
module MEM_DAT #(
    localparam BUS_OUT_DAT = 6,
    localparam DW          = 8,
    localparam BUS_OUT_REQ = 6,
    localparam BUS_OUT_RSP = 4
) (
    // ----- ----- ----- ----- ----- -----
    // 大位宽输入输出
    // ----- ----- ----- ----- ----- -----
    input wire                             bus_in,
    input wire [BUS_OUT_DAT -1:0][DW -1:0] dyadic_bus_out_dat,
    input wire [BUS_OUT_REQ -1:0][DW -1:0] dyadic_bus_out_req,
    input wire [BUS_OUT_RSP -1:0][DW -1:0] dyadic_bus_out_rsp
);

/*USER CODE BEGIN before statement*/

/*USER CODE END   before statement*/
endmodule
