/*USER CODE BEGIN file header*/
//******************
// Design by: aaa
// Project name: bbb
//
//******************
/*USER CODE END   file header*/

// Generated by xlsx2verilog.py. Do not edit outside USER CODE regions.
// `define RST_LANE  1
// `define CLK_LANE  1
// `define DFT_BUS   64
// `define DW_SIG1   114
// `define DW_SIG2   114
// `define DW_SIG3   114
// `define LANE_NUM  3
// `define Test_size 100
// `define Test      100

/*USER CODE BEGIN before module*/

/*USER CODE END   before module*/

module RISCV_TOP #(
    localparam UID_SIZE = 5
) (
    // ----- ----- ----- ----- ----- -----
    // clk & rst
    // ----- ----- ----- ----- ----- -----
    input  wire [`RST_LANE -1:0] n_rst,
    input  wire [`CLK_LANE -1:0] clk,

    // ----- ----- ----- ----- ----- -----
    // dft_sig
    // ----- ----- ----- ----- ----- -----
    input  wire [`DFT_BUS  -1:0] dft_bus,
    input  wire [`DFT_BUS  -1:0] dft_addr,
    input  wire                  dft_test_en,
    input  wire                  dft_out_en,
    input  wire                  dft_rd,

    // ----- ----- ----- ----- ----- -----
    // uid
    // ----- ----- ----- ----- ----- -----
    output wire [UID_SIZE  -1:0] uid,

    // ----- ----- ----- ----- ----- -----
    // AHB_top
    // ----- ----- ----- ----- ----- -----
    input  wire                  ahb_test_1,
    input  wire [2         -1:0] ahb_test_2,
    output wire [3         -1:0] ahb_test_3,
    output wire [4         -1:0] ahb_test_4,
    output wire [5         -1:0] ahb_test_5,
    output wire [6         -1:0] ahb_test_6,

    // ----- ----- ----- ----- ----- -----
    // test_bus
    // ----- ----- ----- ----- ----- -----
    input  wire [`DW_SIG1  -1:0] test_bus_sig1_dat,
    input  wire [`DW_SIG2  -1:0] test_bus_sig2_dat,
    input  wire [`DW_SIG3  -1:0] test_bus_sig3_dat,
    input  wire                  test_bus_sig1_ready,
    input  wire                  test_bus_sig2_ready,
    input  wire                  test_bus_sig3_ready,
    output wire                  test_bus_sig1_valid,
    output wire                  test_bus_sig2_valid,
    output wire                  test_bus_sig3_valid,

    // ----- ----- ----- ----- ----- -----
    // CHI_interface
    // ----- ----- ----- ----- ----- -----
    sky_cs_if.mst                chi_if_risc,

    // ----- ----- ----- ----- ----- -----
    // test_bus2
    // ----- ----- ----- ----- ----- -----
    input  wire [114       -1:0] test_bus2_sig1_dat,
    input  wire [114       -1:0] test_bus2_sig2_dat,
    input  wire [114       -1:0] test_bus2_sig3_dat,
    input  wire                  test_bus2_sig1_ready,
    input  wire                  test_bus2_sig2_ready,
    input  wire [514       -1:0] test_bus2_sig3_ready,
    output wire                  test_bus2_sig1_valid,
    output wire                  test_bus2_sig2_valid,
    output wire                  test_bus2_sig3_valid,
    input  wire [4 -1:0][4 -1:0] test_rx
);

/*USER CODE BEGIN before statement*/

/*USER CODE END   before statement*/

// Integration-local parameters for NA and child-owned widths.
// parameter NA 及子模块位宽上拉创建的 TOP 语句区局部参数。
localparam [8 -1:0][32 -1:0] LOCAL_GEN_VAR_1 = '{default: 1};
localparam [8 -1:0][32 -1:0] LOCAL_GEN_VAR_2 = '{1,2,3,4,5,6,7,8};
localparam LANE_NUM        = 1;
localparam PARAMTER        = 10;

// Internal connections and NA placeholder signals.
// 子模块内部连线及 NA 占位信号。
wire                                   w_apb_1;
wire [2         -1:0]                  w_apb_2;
wire [LANE_NUM  -1:0]                  w_apb_3;
wire [LANE_NUM  -1:0]                  w_apb_4;
wire [LANE_NUM  -1:0]                  w_apb_5;
wire [LANE_NUM  -1:0]                  w_apb_6;
wire [`LANE_NUM -1:0][`Test_size -1:0] w_array;
wire [PARAMTER  -1:0]                  parameter_test;
wire                                   dat_in;
wire                                   sig_out;
wire                        test_bus2_sig3_ready, 

// TOP outputs without an active child driver are tied to zero.
// 没有有效子模块驱动的 TOP 输出在当前配置下置零。
assign uid        = {UID_SIZE{1'b0}};
assign ahb_test_3 = {3{1'b0}};
assign ahb_test_4 = {4{1'b0}};
assign ahb_test_5 = {5{1'b0}};
assign ahb_test_6 = {6{1'b0}};

/*USER CODE BEGIN before RISCV_CORE_TEST*/

/*USER CODE END   before RISCV_CORE_TEST*/
RISCV_CORE_TEST #(
    .LANE_NUM (LANE_NUM)
) U_RISCV_CORE_TEST (
    .n_rst                (n_rst               ),
    .clk                  (clk                 ),
    .dft_test_en          (dft_test_en         ),
    .dft_out_en           (dft_out_en          ),
    .uid                  (uid                 ),
    .ahb_test_1           ({1{1'b0}}           ),
    .ahb_test_2           ({2{1'b0}}           ),
    .ahb_test_3           (                    ),
    .ahb_test_4           (                    ),
    .ahb_test_5           (                    ),
    .apb_1                (w_apb_1             ),
    .apb_2                (w_apb_2             ),
    .apb_3                (w_apb_3             ),
    .apb_4                (w_apb_4             ),
    .apb_5                (w_apb_5             ),
    .apb_6                (w_apb_6             ),
    .test_bus_sig1_dat    (test_bus_sig1_dat   ),
    .test_bus_sig2_dat    (test_bus_sig2_dat   ),
    .test_bus_sig3_dat    (test_bus_sig3_dat   ),
    .test_bus_sig1_ready  (test_bus_sig1_ready ),
    .test_bus_sig2_ready  (test_bus_sig2_ready ),
    .test_bus_sig3_ready  (test_bus_sig3_ready ),
    .test_bus_sig1_valid  (test_bus_sig1_valid ),
    .test_bus_sig2_valid  (test_bus_sig2_valid ),
    .test_bus_sig3_valid  (test_bus_sig3_valid ),
    .chi_if_risc          (chi_if_risc         ),
    .array                (w_array             ),
    .test_bus2_sig1_dat   (test_bus2_sig1_dat  ),
    .test_bus2_sig2_dat   (test_bus2_sig2_dat  ),
    .test_bus2_sig3_dat   (test_bus2_sig3_dat  ),
    .test_bus2_sig1_ready (test_bus2_sig1_ready),
    .test_bus2_sig2_ready (test_bus2_sig2_ready),
    .test_bus2_sig3_ready (test_bus2_sig3_ready),
    .test_bus2_sig1_valid (test_bus2_sig1_valid),
    .test_bus2_sig2_valid (test_bus2_sig2_valid),
    .test_bus2_sig3_valid (test_bus2_sig3_valid),
    .test_rx              (test_rx)
);

/*USER CODE BEGIN after RISCV_CORE_TEST*/

/*USER CODE END   after RISCV_CORE_TEST*/

/*USER CODE BEGIN before MEM_PHY*/

/*USER CODE END   before MEM_PHY*/
MEM_PHY #(
    .PARAMTER (PARAMTER)
) U_MEM_PHY (
    .n_rst               (n_rst              ),
    .clk                 (clk                ),
    .dft_bus             (dft_bus            ),
    .dft_addr            (dft_addr           ),
    .dft_test_en         (dft_test_en        ),
    .dft_out_en          (dft_out_en         ),
    .uid                 (uid                ),
    .apb_1               (w_apb_1            ),
    .apb_2               (w_apb_2            ),
    .apb_3               (w_apb_3            ),
    .apb_4               (w_apb_4            ),
    .apb_5               (w_apb_5            ),
    .apb_6               (w_apb_6            ),
    .ahb_test_1          ({1{1'b0}}          ),
    .ahb_test_2          ({2{1'b0}}          ),
    .ahb_test_3          (                   ),
    .ahb_test_4          (                   ),
    .ahb_test_5          (                   ),
    .test_bus_sig1_dat   (test_bus_sig1_dat  ),
    .test_bus_sig2_dat   (test_bus_sig2_dat  ),
    .test_bus_sig3_dat   (test_bus_sig3_dat  ),
    .test_bus_sig1_ready (test_bus_sig1_ready),
    .test_bus_sig2_ready (test_bus_sig2_ready),
    .test_bus_sig3_ready (test_bus_sig3_ready),
    .test_bus_sig1_valid (test_bus_sig1_valid),
    .test_bus_sig2_valid (test_bus_sig2_valid),
    .test_bus_sig3_valid (test_bus_sig3_valid),
    .array               (w_array            ),
    .parameter_test      (parameter_test     ) //TODO:本信号期望有逻辑功能，请完成
);

/*USER CODE BEGIN after MEM_PHY*/

/*USER CODE END   after MEM_PHY*/

/*USER CODE BEGIN before GEN_PHY*/

/*USER CODE END   before GEN_PHY*/
genvar i_gen_gen_phy_u;
generate
for (i_gen_gen_phy_u = 0; i_gen_gen_phy_u < 8; i_gen_gen_phy_u = i_gen_gen_phy_u + 1) begin : G_GEN_PHY_U
GEN_PHY #(
    .GEN_VAR_1 (LOCAL_GEN_VAR_1[i_gen_gen_phy_u]),
    .GEN_VAR_2 (LOCAL_GEN_VAR_2[i_gen_gen_phy_u])
) GEN_PHY_U (
    .dat_in  (dat_in ), //TODO:本信号期望有逻辑功能，请完成
    .sig_out (sig_out), //TODO:本信号期望有逻辑功能，请完成
    .test_rx (test_rx[0][0]),
    .test_tx (test_rx[0][i])
);
end
endgenerate

/*USER CODE BEGIN after GEN_PHY*/

/*USER CODE END   after GEN_PHY*/
endmodule
