/*USER CODE BEGIN file header*/
//******************
// Design by: aaa
// Project name: bbb
//
//******************
/*USER CODE END   file header*/

// Generated by xlsx2verilog.py. Do not edit outside USER CODE regions.
// `define GLB_RST_LANE   1
// `define RST_LANE       5
// `define CLK_LANE       5
// `define DFT_BUS        64
// `define DW_VERI_DAT    32
// `define DW_VERI_REQ    32
// `define DW_VERI_REQEXT 32
// `define APB_1          4
// `define LANE_NUM       5
// `define TEST_SIZE      100
// `define APB_1_MEM      3
// `define LANE_NUM_MEM   3
// `define TEST           100

module RISCV_TOP #(
    localparam RST_LANE    = `GLB_RST_LANE,  // 1
    localparam CLK_LANE    = 1,
    localparam UID_SIZE    = 5,
    localparam DW_SIG1     = 11,
    localparam DW_SIG2     = 12,
    localparam DW_SIG3     = 13,
    localparam BUS_IN      = 5,
    localparam BUS_OUT_DAT = 32,
    localparam DW          = 8,
    localparam BUS         = 5,
    localparam BUS_OUT_REQ = 32,
    localparam BUS_OUT_RSP = 64
) (
    // ----- ----- ----- ----- ----- -----
    // clk & rst
    // ----- ----- ----- ----- ----- -----
    input  wire [`RST_LANE       -1:0]                    n_rst,
    input  wire [`CLK_LANE       -1:0]                    clk,

    // ----- ----- ----- ----- ----- -----
    // dft_sig
    // ----- ----- ----- ----- ----- -----
    input  wire [`DFT_BUS        -1:0]                    dft_bus,
    input  wire [`DFT_BUS        -1:0]                    dft_addr,
    input  wire [5               -1:0]                    dft_test_en,
    input  wire                                           dft_out_en,
    input  wire                                           dft_rd,

    // ----- ----- ----- ----- ----- -----
    // uid
    // ----- ----- ----- ----- ----- -----
    output wire [UID_SIZE        -1:0]                    uid,

    // ----- ----- ----- ----- ----- -----
    // AHB_top
    // ----- ----- ----- ----- ----- -----
    input  wire                                           ahb_test_1,
    input  wire [2               -1:0]                    ahb_test_2,
    output wire [3               -1:0]                    ahb_test_3,
    output wire [4               -1:0]                    ahb_test_4,
    output wire [5               -1:0]                    ahb_test_5,
    output wire [6               -1:0]                    ahb_test_6,

    // ----- ----- ----- ----- ----- -----
    // test_bus
    // ----- ----- ----- ----- ----- -----
    input  wire [DW_SIG1         -1:0]                    test_bus_sig1_dat,
    input  wire [DW_SIG2         -1:0]                    test_bus_sig2_dat,
    input  wire [DW_SIG3         -1:0]                    test_bus_sig3_dat,
    input  wire                                           test_bus_sig1_ready,
    input  wire                                           test_bus_sig2_ready,
    input  wire                                           test_bus_sig3_ready,
    output wire                                           test_bus_sig1_valid,
    output wire                                           test_bus_sig2_valid,
    output wire                                           test_bus_sig3_valid,

    // ----- ----- ----- ----- ----- -----
    // CHI_interface
    // ----- ----- ----- ----- ----- -----
    sky_cs_if.mst                                         chi_if_risc,

    // ----- ----- ----- ----- ----- -----
    // test_bus2
    // ----- ----- ----- ----- ----- -----
    input  wire [114             -1:0]                    test_bus2_sig1_dat,
    input  wire [114             -1:0]                    test_bus2_sig2_dat,
    input  wire [114             -1:0]                    test_bus2_sig3_dat,
    input  wire                                           test_bus2_sig1_ready,
    input  wire                                           test_bus2_sig2_ready,
    input  wire                                           test_bus2_sig3_ready,
    output wire                                           test_bus2_sig1_valid,
    output wire                                           test_bus2_sig2_valid,
    output wire                                           test_bus2_sig3_valid,

    // ----- ----- ----- ----- ----- -----
    // 大位宽输入输出
    // ----- ----- ----- ----- ----- -----
    input  wire [BUS_IN          -1:0]                    bus_in,
    output wire [BUS_OUT_DAT     -1:0][DW -1:0][BUS -1:0] dyadic_bus_out_dat,
    output reg [BUS_OUT_REQ     -1:0][DW -1:0][BUS -1:0] dyadic_bus_out_req,
    output wire [BUS_OUT_RSP     -1:0][DW -1:0][BUS -1:0] dyadic_bus_out_rsp,

    // ----- ----- ----- ----- ----- -----
    // For verif
    // ----- ----- ----- ----- ----- -----
    output reg [`DW_VERI_DAT    -1:0]                    verification_sig_dat_tie0,
    output wire [`DW_VERI_REQ    -1:0]                    verification_sig_req_tie0,
    output reg [`DW_VERI_REQEXT -1:0]                    verification_sig_reqext_tie0
);

/*USER CODE BEGIN before statement*/
lalalalal
lalalal
lalal
/*USER CODE END   before statement*/

// Internal connections and NA placeholder signals.
// 子模块内部连线及 NA 占位信号。
wire [4               -1:0]                  w_apb_1;
wire [12              -1:0]                  w_apb_21111;
reg [13              -1:0]                  w_apb_3;
wire [14              -1:0]                  w_apb_4;
wire [15              -1:0]                  w_apb_5;
wire [16              -1:0]                  w_apb_6;
wire [`LANE_NUM       -1:0][`TEST_SIZE -1:0] w_array;
wire [13              -1:0]                  ready_test_process;
wire [`DW_VERI_DAT    -1:0]                  w_verification_sig_dat;
wire [`DW_VERI_REQ    -1:0]                  w_verification_sig_req;
wire [`DW_VERI_REQEXT -1:0]                  w_verification_sig_reqext;
wire [12              -1:0]                  w_need_to_solve;
wire [1               -1:0][1          -1:0] high_clk_after_pll_0;
wire [1               -1:0][1          -1:0] high_clk_after_pll_1;
wire [1               -1:0][1          -1:0] high_clk_after_pll_2;
wire [1               -1:0][1          -1:0] high_clk_after_pll_3;
wire [1               -1:0][1          -1:0] high_clk_after_pll_4;
wire [1               -1:0][1          -1:0] high_clk_after_pll_5;
wire [1               -1:0][1          -1:0] high_clk_after_pll_6;
wire [1               -1:0][1          -1:0] high_clk_after_pll_7;
wire [1               -1:0][1          -1:0] high_clk_after_pll_8;
wire [1               -1:0][1          -1:0] high_clk_after_pll_9;
wire [1               -1:0][1          -1:0] high_clk_after_pll_10;
wire [1               -1:0][1          -1:0] high_clk_after_pll_11;
wire [1               -1:0][1          -1:0] high_clk_after_pll_12;
wire [1               -1:0][1          -1:0] high_clk_after_pll_13;
wire [1               -1:0][1          -1:0] high_clk_after_pll_14;
wire [1               -1:0][1          -1:0] high_clk_after_pll_15;
wire [1               -1:0][1          -1:0] high_clk_after_pll_16;
wire [1               -1:0][1          -1:0] high_clk_after_pll_17;
wire [1               -1:0][1          -1:0] high_clk_after_pll_18;
wire [1               -1:0][1          -1:0] high_clk_after_pll_19;
wire [1               -1:0][1          -1:0] high_clk_after_pll_20;
wire [1               -1:0][1          -1:0] high_clk_after_pll_21;
wire [1               -1:0][1          -1:0] high_clk_after_pll_22;
wire [1               -1:0][1          -1:0] high_clk_after_pll_23;
wire [1               -1:0][1          -1:0] high_clk_after_pll_24;
wire [1               -1:0][1          -1:0] high_clk_after_pll_25;
wire [1               -1:0][1          -1:0] high_clk_after_pll_26;
wire [1               -1:0][1          -1:0] high_clk_after_pll_27;
wire [1               -1:0][1          -1:0] high_clk_after_pll_28;
wire [1               -1:0][1          -1:0] high_clk_after_pll_29;
wire [1               -1:0][1          -1:0] high_clk_after_pll_30;
wire [1               -1:0][1          -1:0] high_clk_after_pll_31;

// Width adapters: keep low bits and zero-fill undriven high bits.
// 位宽适配：保留低位，未驱动的高位补零。
assign test_bus2_sig1_valid = {1{1'b1}};
assign test_bus2_sig2_valid = {1{1'b1}};
assign test_bus2_sig3_valid = {1{1'b1}};
assign w_apb_1[4-1:3]       = '0;
assign w_apb_2[12-1:2]      = '0;

// TOP outputs without an active child driver are tied to zero.
// 没有有效子模块驱动的 TOP 输出在当前配置下置零。
assign uid                          = {UID_SIZE{1'b0}};
assign ahb_test_3                   = 3'b0;
assign ahb_test_4                   = 4'b0;
assign ahb_test_5                   = 5'b0;
assign ahb_test_6                   = 6'b0;
assign dyadic_bus_out_dat           = '0;
assign dyadic_bus_out_req           = '0;
assign dyadic_bus_out_rsp           = '0;
assign verification_sig_dat_tie0    = {`DW_VERI_DAT{1'b0}};
assign verification_sig_req_tie0    = {`DW_VERI_REQ{1'b0}};
assign verification_sig_reqext_tie0 = {`DW_VERI_REQEXT{1'b0}};

/*USER CODE BEGIN before RISCV_CORE_TEST*/

/*USER CODE END   before RISCV_CORE_TEST*/
RISCV_CORE_TEST #(
    .RST_LANE (RST_LANE),
    .CLK_LANE (CLK_LANE)
) U_RISCV_CORE_TEST (
    .n_rst                   (n_rst[1]                 ),
    .clk                     (clk[0]                   ),
    .dft_test_en             (dft_test_en[0]           ),
    .dft_out_en              (dft_out_en               ),
    .uid                     (uid                      ),
    .ahb_test_1              (1'b0                     ),
    .ahb_test_2              (2'b0                     ),
    .ahb_test_3              (                         ),
    .ahb_test_4              (                         ),
    .ahb_test_5              (                         ),
    .apb_1                   (w_apb_1                  ),
    .apb_2                   (w_apb_2                  ),
    .apb_3                   (w_apb_3                  ),
    .apb_4                   (w_apb_4                  ),
    .apb_5                   (w_apb_5                  ),
    .apb_6                   (w_apb_6                  ),
    .test_bus_sig1_dat       (test_bus_sig1_dat        ),
    .test_bus_sig2_dat       (test_bus_sig2_dat        ),
    .test_bus_sig3_dat       (test_bus_sig3_dat        ),
    .test_bus_sig1_ready     (test_bus_sig1_ready      ),
    .test_bus_sig2_ready     (test_bus_sig2_ready      ),
    .test_bus_sig3_ready     (test_bus_sig3_ready      ),
    .test_bus_sig1_valid     (test_bus_sig1_valid      ),
    .test_bus_sig2_valid     (test_bus_sig2_valid      ),
    .test_bus_sig3_valid     (test_bus_sig3_valid      ),
    .chi_if_risc             (chi_if_risc              ),
    .array                   (w_array                  ),
    .array_2                 (                         ),
    .test_bus2_sig1_dat      (test_bus2_sig1_dat       ),
    .test_bus2_sig2_dat      (test_bus2_sig2_dat       ),
    .test_bus2_sig3_dat      (test_bus2_sig3_dat       ),
    .test_bus2_sig1_ready    (test_bus2_sig1_ready     ),
    .test_bus2_sig2_ready    (test_bus2_sig2_ready     ),
    .test_bus2_sig3_ready    (test_bus2_sig3_ready     ),
    .test_bus2_sig1_valid    (                         ),
    .test_bus2_sig2_valid    (                         ),
    .test_bus2_sig3_valid    (                         ),
    .ready_to_process        (ready_test_process       ), //TODO:本信号期望有逻辑功能，请完成
    .verification_sig_dat    (w_verification_sig_dat   ),
    .verification_sig_req    (w_verification_sig_req   ),
    .verification_sig_reqext (w_verification_sig_reqext)
);

/*USER CODE BEGIN after RISCV_CORE_TEST*/

/*USER CODE END   after RISCV_CORE_TEST*/

/*USER CODE BEGIN before MEM_PHY*/

/*USER CODE END   before MEM_PHY*/
MEM_PHY U_MEM_PHY (
    .n_rst                   (n_rst[0]                 ),
    .clk                     (clk[0]                   ),
    .dft_bus                 (dft_bus                  ),
    .dft_addr                (dft_addr                 ),
    .dft_test_en             (dft_test_en[0]           ),
    .dft_out_en              (dft_out_en               ),
    .uid                     (uid                      ),
    .apb_1                   (w_apb_1[3 -1:0]          ),
    .apb_2                   (w_apb_2[2 -1:0]          ),
    .apb_3                   (w_apb_3[3 -1:0]          ),
    .apb_4                   (w_apb_4[4 -1:0]          ),
    .apb_5                   (w_apb_5[5 -1:0]          ),
    .apb_6                   (w_apb_6[6 -1:0]          ),
    .ahb_test_1              (1'b0                     ),
    .ahb_test_2              (2'b0                     ),
    .ahb_test_3              (                         ),
    .ahb_test_4              (                         ),
    .ahb_test_5              (                         ),
    .test_bus_sig1_dat       (test_bus_sig1_dat        ),
    .test_bus_sig2_dat       (test_bus_sig2_dat        ),
    .test_bus_sig1_ready     (test_bus_sig1_ready      ),
    .test_bus_sig2_ready     (test_bus_sig2_ready      ),
    .test_bus_sig1_valid     (test_bus_sig1_valid      ),
    .test_bus_sig2_valid     (test_bus_sig2_valid      ),
    .array                   (w_array                  ),
    .need_to_solve           (w_need_to_solve          ),
    .verification_sig_dat    (w_verification_sig_dat   ),
    .verification_sig_req    (w_verification_sig_req   ),
    .verification_sig_reqext (w_verification_sig_reqext)
);

/*USER CODE BEGIN after MEM_PHY*/

/*USER CODE END   after MEM_PHY*/

/*USER CODE BEGIN before MEM_DAT*/

/*USER CODE END   before MEM_DAT*/
genvar i_gen_project_personal_mem_dat;
generate
for (i_gen_project_personal_mem_dat = 0; i_gen_project_personal_mem_dat < 5; i_gen_project_personal_mem_dat = i_gen_project_personal_mem_dat + 1) begin : G_PROJECT_PERSONAL_MEM_DAT
MEM_DAT PROJECT_PERSONAL_MEM_DAT (
    .bus_in             (bus_in            [i_gen_project_personal_mem_dat]),
    .dyadic_bus_out_dat (dyadic_bus_out_dat[i_gen_project_personal_mem_dat]),
    .dyadic_bus_out_req (dyadic_bus_out_req[i_gen_project_personal_mem_dat]),
    .dyadic_bus_out_rsp (dyadic_bus_out_rsp[i_gen_project_personal_mem_dat])
);
end
endgenerate

/*USER CODE BEGIN after MEM_DAT*/

/*USER CODE END   after MEM_DAT*/

/*USER CODE BEGIN before RISCV_CRG*/

/*USER CODE END   before RISCV_CRG*/
genvar i_gen_u_riscv_crg;
generate
for (i_gen_u_riscv_crg = 0; i_gen_u_riscv_crg < 1; i_gen_u_riscv_crg = i_gen_u_riscv_crg + 1) begin : G_U_RISCV_CRG
RISCV_CRG U_RISCV_CRG (
    .clk                   (w_need_to_solve                         ),
    .high_clk_after_pll_0  (high_clk_after_pll_0 [i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_1  (high_clk_after_pll_1 [i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_2  (high_clk_after_pll_2 [i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_3  (high_clk_after_pll_3 [i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_4  (high_clk_after_pll_4 [i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_5  (high_clk_after_pll_5 [i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_6  (high_clk_after_pll_6 [i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_7  (high_clk_after_pll_7 [i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_8  (high_clk_after_pll_8 [i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_9  (high_clk_after_pll_9 [i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_10 (high_clk_after_pll_10[i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_11 (high_clk_after_pll_11[i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_12 (high_clk_after_pll_12[i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_13 (high_clk_after_pll_13[i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_14 (high_clk_after_pll_14[i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_15 (high_clk_after_pll_15[i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_16 (high_clk_after_pll_16[i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_17 (high_clk_after_pll_17[i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_18 (high_clk_after_pll_18[i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_19 (high_clk_after_pll_19[i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_20 (high_clk_after_pll_20[i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_21 (high_clk_after_pll_21[i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_22 (high_clk_after_pll_22[i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_23 (high_clk_after_pll_23[i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_24 (high_clk_after_pll_24[i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_25 (high_clk_after_pll_25[i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_26 (high_clk_after_pll_26[i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_27 (high_clk_after_pll_27[i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_28 (high_clk_after_pll_28[i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_29 (high_clk_after_pll_29[i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_30 (high_clk_after_pll_30[i_gen_u_riscv_crg]), //TODO:本信号期望有逻辑功能，请完成
    .high_clk_after_pll_31 (high_clk_after_pll_31[i_gen_u_riscv_crg]) //TODO:本信号期望有逻辑功能，请完成
);
end
endgenerate

/*USER CODE BEGIN after RISCV_CRG*/

/*USER CODE END   after RISCV_CRG*/
endmodule
